<?php

namespace App;

use App\helper\mathParser\Math;
use App\helper\PaymentModelHelper;
use Illuminate\Database\Eloquent\Model;
use function foo\func;

class Employee extends Model
{
    //
    protected $guarded = [];
    public static function employeeRoles()
    {
        return[
            'admin','not admin'
        ];
    }

    public function address()
    {
        return $this->morphOne(Address::class,'addressable');
    }

    public function centers()
    {
        return $this->belongsTo(Center::class);
    }

    public function jobs()
    {
        return $this->belongsToMany(Job::class);
    }

    public function paymentModel()
    {
        return $this->belongsTo(PaymentModel::class);
    }

    public function setPaymentModelMetaDataAttribute($meta_data)
    {
        return $this->attributes['payment_model_meta_data'] = json_encode($meta_data,JSON_UNESCAPED_UNICODE );
    }

    public function getPaymentModelMetaDataAttribute($meta_data)
    {
        return json_decode($meta_data, true);
    }

    public function getPaymentModelAttribute($paymentModel)
    {

        PaymentModelHelper::getPaymentModelAttribute($this, $paymentModel);

    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleting(function($employee){
            $employee->address->delete();
        });
    }
}
