<?php

namespace App;

use App\helper\Constants;
use App\helper\ImageUploader;
use App\helper\MathParser\Math;
use App\helper\PaymentModelHelper;
use App\QueryFilter\SearchBy;
use App\QueryFilter\Sort;
use App\Rules\DegreeRule;
use App\Rules\FacultyRule;
use App\Rules\UniquePerCenter;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;
use Illuminate\Pipeline\Pipeline;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Str;
use phpDocumentor\Reflection\Types\Integer;


class Instructor extends ImageUploader
{
    protected $hidden = array('pivot');

    protected $guarded = [];
    protected $appends = ['total'];


    public static function allInstructors($center)
    {
        return App(Pipeline::class)
            ->send($center->instructors())
            ->through([
                SearchBy::class,
                Sort::class

            ])
            ->thenReturn()
            ->get();
    }

    public function getImage($key)
    {
        $imagePath = ($this->$key) ? $this->$key : Constants::getInstructorPlaceholderImage();
        return $imagePath;
    }



    public function centers(){
        return $this->belongsToMany(Center::class);
    }

    public function courses()
    {
        return $this->belongsToMany(Course::class);
    }

    public function diplomaGroups()
    {
        return $this->hasMany(DiplomaGroup::class);
    }

    public function busyTimes()
    {
        $groups = $this->diplomaGroups;
        $busyTimes = [];
        foreach ($groups as $group){
            foreach ($group->times as $time){
                $busyTimes[] = $time;
            }
        }
        return collect($busyTimes);
    }

    public function address()
    {
        return $this->morphOne(Address::class,'addressable');
    }

    public function getAddress($address)
    {
        $address->state = State::where('state_id', $address->state)->where('lang', 'ar')->first()->name;
        $address->city = City::where('city_id', $address->city)->where('lang', 'ar')->first()->name;
        return $address;
    }

    // save image before center it to db
    public function setImageAttribute($image){
        $this->deleteImage($this->image);
        $original = $this->saveImage($image);
        return $this->attributes['image'] = url($this->getDir()."/".$original);

    }
    public function setIdImageAttribute($idImage){
        $this->deleteImage($this->idImage);
        $original = $this->saveImage($idImage);
        return $this->attributes['idImage'] = url($this->getDir()."/".$original);

    }

    // get last rest for instructor
    public function getTotalAttribute()
    {
        $center = Center::findOrFail(Session('center_id'));
        $rest = $center->transactions()->where("meta_data->payFor_type", "App\Instructor")
            ->where("meta_data->payFor_id", "$this->id")->latest()->first()['rest'];
        return $this['total'] = $rest + $this->payment_model['salary'];
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleting(function ($instructor){

            // detach the student from all centers
            foreach ($instructor->centers as $center){
                $center->instructors()->detach($instructor);
            }
            // delete student's address
            if($instructor->address) $instructor->address->delete();
            // delete student's image and id_image from /uploads/profiles
            if($instructor->image) (new self)->deleteImage($instructor->image);
            if($instructor->idImage) (new self)->deleteImage($instructor->idImage);

        });
    }

    public function paymentModel()
    {
        return $this->belongsTo(PaymentModel::class);
    }


    public function setPaymentModelMetaDataAttribute($meta_data)
    {
        return $this->attributes['payment_model_meta_data'] = json_encode($meta_data,JSON_UNESCAPED_UNICODE );
    }


    public function getPaymentModelAttribute($paymentModel)
    {
        return PaymentModelHelper::getPaymentModelAttribute($paymentModel,
            json_decode($this->payment_model_meta_data, true));
    }



    public static function ApiFields(){
        return ['instructors.id','nameAr','nameEn','image','bio'];
    }


    public function getDir()
    {
        return '/uploads/profiles';
    }

    public static function rules(Request $request)
    {

        if($request->isMethod('post')){
            return [
                'nameAr' => ['required', new UniquePerCenter(Instructor::class, '', 'instructors', false)],
                'nameEn' => ['required', new UniquePerCenter(Instructor::class, '', 'instructors', false)],
                'email' => ['required', new UniquePerCenter(Instructor::class, '', 'instructors', false)],
                'idNumber' => ['required', 'digits:14', new UniquePerCenter(Instructor::class, '', 'instructors', false)],
                'image' => ' required|image|file | max:10000',
                'idImage' => 'required|image|file | max:10000',
                'phoneNumber' => ['required', 'regex:/(01)[0-9]{9}/', new UniquePerCenter(Instructor::class, '', 'instructors', false)],
//                'phoneNumberSec' => 'sometimes|regex:/(01)[0-9]{9}/',
                'passportNumber' => 'sometimes',
                'state' => 'sometimes',
                'city' => 'required',
                'address' => 'required',
                'bio' => 'nullable',
                'payment_model' => ['required', 'integer'],
                'payment_model_meta_data' => ['required', 'array'],
            ];
        }else{
            $instructor_id = $request->route('instructor')->id;
            return[
                'nameAr' => ['required', new UniquePerCenter(Instructor::class, $instructor_id, 'instructors', false)],
                'nameEn' => ['required', new UniquePerCenter(Instructor::class, $instructor_id, 'instructors', false)],
                'email' => ['required', new UniquePerCenter(Instructor::class, $instructor_id, 'instructors', false)],
                'idNumber' => ['required', 'digits:14', new UniquePerCenter(Instructor::class, $instructor_id, 'instructors', false)],
                'image' => ' sometimes|image|file | max:10000',
                'idImage' => 'sometimes|image|file | max:10000',
                'phoneNumber' => ['required', 'regex:/(01)[0-9]{9}/', new UniquePerCenter(Instructor::class, $instructor_id, 'instructors', false)],
//                'phoneNumberSec' => 'sometimes|regex:/(01)[0-9]{9}/',
                'passportNumber' => 'sometimes',
                'state' => 'sometimes',
                'city' => 'sometimes',
                'address' => 'sometimes',
                'bio' => 'nullable',
                'payment_model' => ['required', 'integer'],
                'payment_model_meta_data' => ['required', 'array'],
            ];
        }
    }

}
