<?php

namespace App;

use App\QueryFilter\Id;
use App\QueryFilter\SearchBy;
use App\QueryFilter\Sort;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Pipeline\Pipeline;

class Test extends Model
{
    protected $guarded  = [];

    public static function allTests($center)
    {
        return app(Pipeline::class)
            ->send($center->tests()->with('groups.enrollers'))
            ->through([
                Id::class,
                SearchBy::class,
                Sort::class
            ])
            ->thenReturn()
            ->paginate(5);
    }

    public function center()
    {
        return $this->belongsTo(Center::class);

    }

    public function groups()
    {
        return $this->hasMany(TestGroup::class)->with('times');

    }



    public function categories()
    {
        return $this->morphToMany(Category::class, 'categorical', 'categorical');
    }
    public function statement()
    {
        return $this->hasOne(TestStatement::class);
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleting(function ($test){

            // delete test groups times
            $test->groups->each(function ($group){
                $group->times()->detach();
            });



        });
    }

}
